# -*- coding: utf-8 -*-
"""face emotion dector.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1JTU8vn0obXh7h8QY9V83ntkPIjCs-nCZ
"""
# major contributor : Parth Patwari
pip install deepface

from deepface import DeepFace

face_analysis_2 = DeepFace.analyze(img_path="happy2.webp")
print(face_analysis_2)

